apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-demo-flux
  namespace: default
  labels:
    app: webapp-demo-flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-demo-flux
  template:
    metadata:
      labels:
        app: webapp-demo-flux  
    spec:
      containers:
      - name: webapp-demo-flux
        image: 520044189785.dkr.ecr.us-west-2.amazonaws.com/webapp:93d643dd
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
