name: Auto PR
on: 
  push:
    branches:
      - 'release/production/**'
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
      - '**/.gitignore'

jobs:
  build-push:
    name: Auto PR
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Create pull request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "${{ github.ref_name }}"
        pr_body: |
          ${{ github.event.head_commit.message }}
        pr_label: "auto-pr"
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
        pr_reviewer: "EzzioMoreira"